services:
  - type: web
    name: ikart
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn ikart.wsgi:application
    healthCheckPath: /healthz/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: SITE_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
