from django.urls import path
from . import views

app_name = "storefront"
urlpatterns = [
    path("", views.home, name="home"),
    path("shop/", views.product_list, name="product_list"),
    path("shop/autocomplete/", views.search_autocomplete, name="search_autocomplete"),
    path("category/<slug:category_slug>/", views.product_list, name="category"),
    path("product/<slug:slug>/", views.product_detail, name="product_detail"),
    path("product/<int:product_id>/cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/", views.cart_detail, name="cart"),
    path("cart/update/", views.update_cart, name="update_cart"),
    path("cart/update-quote/", views.update_cart_quote, name="update_cart_quote"),
    path("cart/coupon/", views.update_coupon_quote, name="update_coupon_quote"),
    path("cart/remove/<path:key>/", views.remove_from_cart, name="remove_from_cart"),
    path("cart/save/<path:key>/", views.save_cart_item_for_later, name="save_cart_item_for_later"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("wishlist/toggle/<int:product_id>/", views.toggle_wishlist, name="toggle_wishlist"),
    path("saved-for-later/", views.saved_for_later, name="saved_for_later"),
    path("saved-for-later/<int:item_id>/move/", views.move_saved_item_to_cart, name="move_saved_item_to_cart"),
    path("saved-for-later/<int:item_id>/remove/", views.remove_saved_item, name="remove_saved_item"),
    path("addresses/", views.addresses, name="addresses"),
    path("addresses/<int:address_id>/edit/", views.edit_address, name="edit_address"),
    path("addresses/<int:address_id>/delete/", views.delete_address, name="delete_address"),
    path("checkout/", views.checkout, name="checkout"),
    path("payment/<str:number>/", views.payment_checkout, name="payment_checkout"),
    path("payment/<str:number>/return/", views.razorpay_payment_link_callback, name="razorpay_payment_link_callback"),
    path("payment/<str:number>/verify/", views.verify_razorpay_payment, name="verify_razorpay_payment"),
    path("payment/<str:number>/cancel/", views.cancel_razorpay_payment, name="cancel_razorpay_payment"),
    path("payment/<str:number>/event/", views.razorpay_checkout_event, name="razorpay_checkout_event"),
    path("payments/razorpay/webhook/", views.razorpay_webhook, name="razorpay_webhook"),
    path("order/<str:number>/", views.order_confirmation, name="order_confirmation"),
    path("orders/", views.order_history, name="order_history"),
    path("order/<str:number>/<str:request_type>/", views.request_order_change, name="request_order_change"),
    path("signup/", views.signup, name="signup"),
    path("verify-email/", views.verify_email, name="verify_email"),
    path("verify-email/resend/", views.resend_verification_code, name="resend_verification_code"),
    path("product/<slug:slug>/review/", views.add_review, name="add_review"),
    path("product/<slug:slug>/question/", views.add_product_question, name="add_product_question"),
    path("support/", views.support_center, name="support"),
    path("support/<int:ticket_id>/", views.support_ticket, name="support_ticket"),
    path("notification-preferences/", views.notification_preferences, name="notification_preferences"),
    path("dashboard/analytics/", views.analytics_dashboard, name="analytics_dashboard"),
    path("<slug:page>/", views.trust_page, name="trust_page"),
]
