# Generated by Django 5.2.16 on 2026-07-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
