# Generated by Django 5.2.16 on 2026-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_coupon_faq_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingpreference',
            name='email_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
