# Generated by Django 5.2.16 on 2026-07-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_paymentwebhookevent_order_checkout_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('refund_pending', 'Refund pending'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('refund_pending', 'Refund pending'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
