# Generated by Django 5.2.17 on 2026-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0008_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_payment_link_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_order_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
