# Generated by Django 5.2.17 on 2026-09-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0010_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("payment_pending", "Payment pending"),
                    ("payment_failed", "Payment failed"),
                    ("placed", "Placed"),
                    ("shipped", "Shipped"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("cancellation_requested", "Cancellation requested"),
                    ("return_requested", "Return requested"),
                    ("refunded", "Refunded"),
                ],
                default="placed",
                max_length=30,
            ),
        ),
    ]
