# Generated by Django 6.1 on 2026-09-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0011_alter_order_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow",
                    models.CharField(default="Thoughtfully curated", max_length=100),
                ),
                (
                    "headline",
                    models.CharField(
                        default="Quality fashion,\nmade accessible.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="Discover a carefully selected collection of timeless pieces. Every item chosen for quality, style, and value.",
                        max_length=500,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero section background/illustration image",
                        null=True,
                        upload_to="hero/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
        ),
    ]
