# Generated by Django 6.1 on 2026-09-27 07:50

from django.db import migrations, models
from django.db.models import F


def backfill_delivered_at(apps, schema_editor):
    # Best available record of when these were marked delivered.
    Order = apps.get_model("storefront", "Order")
    Order.objects.filter(status="delivered", delivered_at__isnull=True).update(delivered_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0012_herosection"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_delivered_at, migrations.RunPython.noop),
    ]
