# Generated by Django 5.2.17 on 2026-09-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0015_drop_orphan_sms_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary_variant_attribute",
            field=models.CharField(
                blank=True,
                help_text="Which variant attribute to display as buttons (e.g. size, color, storage, material). Leave blank to use dropdown.",
                max_length=40,
            ),
        ),
    ]
