# Generated by Django 5.2.17 on 2026-09-28 04:52

from django.db import migrations


def set_primary_variant_attributes(apps, schema_editor):
    """Set primary_variant_attribute to 'size' for products with size variants."""
    Product = apps.get_model("storefront", "Product")

    for product in Product.objects.filter(variants__isnull=False).distinct():
        # Check if product has size variants
        has_size = product.variants.filter(size__gt="").exists()
        if has_size:
            product.primary_variant_attribute = "size"
            product.save(update_fields=["primary_variant_attribute"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0016_product_primary_variant_attribute"),
    ]

    operations = [
        migrations.RunPython(set_primary_variant_attributes, noop),
    ]
