# Generated by Django 5.2.17 on 2026-09-28 05:12

from django.db import migrations


def add_shoe_and_shirt_variants(apps, schema_editor):
    """Add size variants for Nike shoe and Cotton T-shirt."""
    Product = apps.get_model("storefront", "Product")
    ProductVariant = apps.get_model("storefront", "ProductVariant")

    # Nike shoe sizes: 5, 6, 7, 8, 9, 10
    nike = Product.objects.filter(name__icontains="Nike Air Max").first()
    if nike:
        sizes = ["5", "6", "7", "8", "9", "10"]
        for i, size in enumerate(sizes):
            ProductVariant.objects.create(
                product=nike,
                size=size,
                sku=f"NIKE-AIR-MAX-{size}",
                stock=10,
                price_adjustment=0,
            )
        nike.primary_variant_attribute = "size"
        nike.save(update_fields=["primary_variant_attribute"])

    # Cotton T-shirt sizes: XS, S, M, L, XL, XXL
    tshirt = Product.objects.filter(name__icontains="Cotton Casual").first()
    if tshirt:
        sizes = ["XS", "S", "M", "L", "XL", "XXL"]
        for size in sizes:
            ProductVariant.objects.create(
                product=tshirt,
                size=size,
                sku=f"COTTON-TSHIRT-{size}",
                stock=15,
                price_adjustment=0,
            )
        tshirt.primary_variant_attribute = "size"
        tshirt.save(update_fields=["primary_variant_attribute"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0017_set_primary_variant_attributes"),
    ]

    operations = [
        migrations.RunPython(add_shoe_and_shirt_variants, noop),
    ]
